### ISSUE TITLE
TCB data structure

### ISSUE THREAD

**Issue by ghost** [elliott-beach/ghi#1]
From what I can tell, these are the fields we need for our TCBs:

int stack_size
array stack;
sig_jmpbuf jbuf
        // Initially, sp will be set to stack + stack_size
        // Initially, pc will be set to the function/stub
int state
        // waiting, running, or blocked

Is there anything else we need to include in each TCB? I think you said we might need a timer to prevent each thread from dominating execution.

Also do you have any opinion on what kind of array we should use to implement the stack to be able to hold different data types? void pointers? or maybe just integers that can later be cast to addresses

**Comment by elliott-beach** [comment]
@kstowe Thanks, I just  the repo with the code so far. I adopted it from one of the examples in class; there's a comment at the top of the file with that info.

Because I couldn't figure out how to properly construct function arguments, I am using a global data structure to store the function to be run in the thread, and other information.

I think we can basically add data to the TCB ad-hoc without damaging our design. 
The stack is a `char*[]`. 

State is a bool, we should modify it.
